### ISSUE TITLE
Improve the order of address in the checkout page 

### ISSUE THREAD

**Issue by htdat** [htdat/woo-viet#17]
Currently, it's like this. 

It should be better: Country - Province - District - Address 

![image](https://cloud.githubusercontent.com/assets/10045087/25274970/12316b20-26bd-11e7-98d0-700c1d114876.png)

**Comment by htdat** [comment]
Requests: 
* https://wordpress.org/support/topic/thay-doi-thu-tu-field-tinh-huyen/

**Comment by wasimodo98** [comment]
Can you update this issue? I like your plugin very much. Thank you!

**Comment by htdat** [comment]
Hi @wasimodo98, 

> Can you update this issue? I like your plugin very much. Thank you!

We have some progress in dealing with this issue. We use CSS and JS for that, it seems to work well. 
However, there are something we need to improve for this PR. You can follow here: 
 
https://github.com/htdat/woo-viet/pull/43

---- 

Btw, another request: https://wordpress.org/support/topic/switching-the-order-of-district-and-province/
