### ISSUE TITLE
 OnePay gateway - International cards 

### ISSUE THREAD

**Issue by htdat** [htdat/woo-viet#21]
https://mtf.onepay.vn/developer/?page=modul_quocte

**Comment by daohoangson** [comment]
Are there any plan to implement this? We are in need of this module and would love to contribute if possible.

**Comment by htdat** [comment]
I am sorry that we have not had any plan yet. 

It's awesome if you can contribute the code. 

I did not research much this international card gateway but it would be similar to the domestic one. 

You can find the code for domestic in this file:

https://github.com/htdat/woo-viet/blob/master/inc/class-wooviet-onepay-domestic.php

and this part of the main file
https://github.com/htdat/woo-viet/blob/master/woo-viet.php#L158-L176

**Comment by daohoangson** [comment]
Thank you for the info. I will open a PR when it's done.

**Comment by htdat** [comment]
Closing this as it's a dupe of #74. 
Anyway, thanks for your comment on #74 @daohoangson :)
