### ISSUE TITLE
Display only Vietnam or even delete the country option in the checkout page

### ISSUE THREAD

**Issue by htdat** [htdat/woo-viet#26]

**Comment by Longkt** [comment]
Note: https://gist.github.com/Longkt/04f572d3a951aed2445fc7d8f405638b

**Comment by Longkt** [comment]
Add more select countries to display on the Checkout page

![screen shot 2018-04-21 at 23 03 18](https://user-images.githubusercontent.com/25312148/39086195-51f277f2-45b8-11e8-8867-901b3c54f82e.png)

**Comment by htdat** [comment]
In Settings wp-admin/admin.php?page=wc-settings&tab=general, there is an option to sell to specific countries: 

![settings](https://user-images.githubusercontent.com/10045087/53299592-e15c6e80-386e-11e9-87bd-531e7b260f6b.png)

Then in Checkout page, it look like this. 

![checkout](https://user-images.githubusercontent.com/10045087/53299593-e4eff580-386e-11e9-8427-0ad94bb80a1e.png)

--- 

All in all, Woo supported this feature already. Closing this GH issue.
