### ISSUE TITLE
1.3.1 - Add the questionnaire after 4 weeks

### ISSUE THREAD

**Issue by htdat** [htdat/woo-viet#29]
Coding: 
- [x] Tech: Add a key to save the time for start using Woo Viet. 
- [x] Tech: After 4 weeks, ask for answering the questions and rating (link to 5 stars).
- [x] Tech: Disable after clicking or Dismiss. Maybe a button. 

Good solutions and info: 

* https://wordpress.stackexchange.com/questions/242705/how-to-stop-showing-admin-notice-after-close-button-has-been-clicked
* https://digwp.com/2016/05/wordpress-admin-notices/

Questionnaire: 
- [x] Questionnaire in both languages - Google Forms
- [x] Are you satisfied? 1 - 2 - 3 - 4 - 5 
- [x] Which features are you using? 
- [x] Which should we improve? Which should we add more?
- [x] Are you willing to provide email and we can contact you in the case we ask more info?
- [x] You can always contribute your ideas at...

**Comment by htdat** [comment]
English: https://goo.gl/forms/N4GxvBtaIg6iryx43

**Comment by htdat** [comment]
Vietnamese: https://goo.gl/forms/QIMkNrRIxgERBBcm2

**Comment by htdat** [comment]
Done!

**Comment by buiquangduc** [comment]
@htdat 
![image](https://user-images.githubusercontent.com/20354417/27814840-b0a772f6-60a9-11e7-8edd-da214d5a7e69.png)

Typo in Vietnamese version of feedback form.

**Comment by htdat** [comment]
@buiquangduc: 

Thank you. Changed it to
`Theo bạn, nhóm phát triển cần làm gì để cải thiện plugin?`
