### ISSUE TITLE
Form Quận Huyện bị ngược và bị lỗi không hiện Quận Huyện khi chọn tỉnh thành

### ISSUE THREAD

**Issue by webkitvn** [htdat/woo-viet#34]
Hi bạn,
Mình bị lỗi trong checkout, mục quận huyện nằm bên trên mục chọn tỉnh thành, khi chọn tỉnh thành thì mục quận huyện không hiện gì cả. 

[http://sv1.upsieutoc.com/2017/07/18/Screenshot11.png](url)

**Comment by htdat** [comment]
> mục quận huyện nằm bên trên mục chọn tỉnh thành
Cái này mình đã note ở đây #17

>  khi chọn tỉnh thành thì mục quận huyện không hiện gì cả.
Mình check thì không có vấn đề gì. Bạn xem ở screenshot bên dưới. 
Bạn thử kiểm tra: tắt hết các plugin, chỉ để lại Woo Viet và WooCommerce?  

![screenshot_2017-07-19__20-51-08](https://user-images.githubusercontent.com/10045087/28370300-1b568b16-6cc4-11e7-917a-fd39bb57f322.png)

Vì không phải là "issue" thực sự, nên mình tạm thời close.
