### ISSUE TITLE
Integrate all districts to Vietnam provinces.

### ISSUE THREAD

**Issue by htdat** [htdat/woo-viet#4]
# Source (data):
* http://banggiadat.vn/

* batdongsan.com.vn => There some ASHX files (JSON format) including this info (even streets). E.g: http://content.batdongsan.com.vn/HandlerWeb/ProductEditServiceHandler.ashx?type=prepairbds4&v=172

* muabannhadat.com 

* http://netdepviet.org/vn/csdl-ten-tinh-thanh-pho-thi-xa-quan-huyen-viet-nam-7454-1-1.html 

# Library for populating districts based on selected provinces 

This might be helpful since WooCommerce does not have the feature to populate a dropdown for the `City` field - https://github.com/8manos/wc-city-select

**Comment by htdat** [comment]
Another good one: https://wordpress.org/plugins/states-cities-and-places-for-woocommerce/changelog/

**Comment by 10h30** [comment]
Hello @htdat ,
I am using WC-City-Select to setup dropdown for Vietnam districts.
Below is the snippet that I consolidated all the districts of Vietnam based on the latest data (http://gso.gov.vn/dmhc2015/Default.aspx)

https://gist.github.com/10h30/7e9307d405ff9ef88cf7d226c90a5d13

**Comment by htdat** [comment]
Awesome. Thanks for your code. I will review it and let you know later.

**Comment by htdat** [comment]
Done!

**Comment by 10h30** [comment]
Thanks for implementing this into the plugin. Now it is easy to add VN provinces to Woo rather than using code.
