### ISSUE TITLE
Test WooViet v1.3.1 and (WooCommerce 3.3.5 and WordPress 4.9.5) - OnePay gateway issue

### ISSUE THREAD

**Issue by Longkt** [htdat/woo-viet#45]
- [x] Add the OnePay Domestic Gateway - OK
- [x] Add provinces, districts for Vietnam - OK
- [x] Add provinces, districts for Vietnam - OK
- [x] Change VND currency symbol - OK
- [x] Convert 000 of prices to K (or anything) - OK

(Edited by @htdat): 
- [x] the OnePay domestic (local ATM cards) gateway

**Comment by Longkt** [comment]
When checkout with OnePay, I found this issue: if I cancel checkout

![28](https://user-images.githubusercontent.com/25312148/38722124-1679d73e-3f27-11e8-8b1c-088eb17cfea6.PNG)

It always returns a notice `Order Received`

![29](https://user-images.githubusercontent.com/25312148/38722232-76c4731a-3f27-11e8-910b-1a7dc4cae5c9.PNG)

But in the backend, the webmaster can know the customer cancel checkout

![30](https://user-images.githubusercontent.com/25312148/38722256-8ece88a6-3f27-11e8-8587-cf4d06824e93.PNG)

I don't know if it was the ideas of the developers to track that order and webmaster can contact this customer by email, phone ... to buy these products again.

**Comment by htdat** [comment]
> Change VND currency symbol
 
What's about this feature? Is it working? 
I do not see you tick this above.

**Comment by htdat** [comment]
For OnePay issue: good reporting and test case! 

It looks like a bug. 

1. What's the status of this order on http://my-site.com/my-account/orders/? I guess it's displaying correctly `Pending Payment`. 

2. Is there any idea to fix this issue? 

---- 

Another comment: when reporting in the public repo like this, try to remove your personal information.

**Comment by Longkt** [comment]
![screen shot 2018-04-15 at 21 44 10](https://user-images.githubusercontent.com/25312148/38779708-35dc437a-40f6-11e8-8b3a-20f98ef495d7.png)

Change VND currency symbol - OK

**Comment by htdat** [comment]
> What's the page you think we should redirect?

@Longkt: Do the research, then let me know what you think first.

**Comment by htdat** [comment]
I've tested on my site. It seems that PayPal is returining back like this when the user clicks "Cancel? 

http://my-test.site/cart/?cancel_order=true&order=wc_order_5ad75de1b7818&order_id=23&redirect&_wpnonce=ec885679e5


![screen shot on 2018-04-18 at 22 10 24](https://user-images.githubusercontent.com/10045087/38940881-81fd3f0a-4355-11e8-9947-290afc27e466.png)

**Comment by htdat** [comment]
>  the OnePay domestic (local ATM cards) gateway
Fixed at #50
