### ISSUE TITLE
Việt hoá tỉnh thành! 

### ISSUE THREAD

**Issue by tranthaihoang** [htdat/woo-viet#59]
Ad Việt hoá tỉnh thành đi, sao huyện có tiếng Việt mà tỉnh thành thì không có dấu, với Việt Hoá luôn 2 cái label tỉnh thành và huyện thì tuyệt vời hơn

**Comment by Longkt** [comment]
Tỉnh thành đã được Việt hóa rồi nhé bạn. Bạn có thể chuyển sang ngôn ngữ Tiếng Việt bằng cách vào
Settings -> General -> Site languague -> Tiếng Việt sau đó lưu lại.

Tiếp theo vào Bảng tin -> Cập nhật -> Dịch, chỗ này sẽ cập nhật tất cả các plugin đã được dịch sang Tiếng Việt trên WordPress.org như Woo Việt, WooCommerce ... @tranthaihoang

**Comment by tranthaihoang** [comment]
> Tỉnh thành đã được Việt hóa rồi nhé bạn. Bạn có thể chuyển sang ngôn ngữ Tiếng Việt bằng cách vào
> Settings -> General -> Site languague -> Tiếng Việt sau đó lưu lại.
> 
> Tiếp theo vào Bảng tin -> Cập nhật -> Dịch, chỗ này sẽ cập nhật tất cả các plugin đã được dịch sang Tiếng Việt trên WordPress.org như Woo Việt, WooCommerce ... @tranthaihoang

Cảm ơn bro! mình vừa thấy bản cập nhật và update rồi, và nó đã ok! cảm ơn nhé

**Comment by htdat** [comment]
👍Cảm ơn 2 bạn, close issue này.
