### ISSUE TITLE
Assigning Shipping Zones By District

### ISSUE THREAD

**Issue by gallnomad** [htdat/woo-viet#71]
Hi, 
We have installed your plugin and I just went to test shipping zones so we can assign shipping costs by district but I cannot see where to do that. Could you let me know if I can? If not do you know of any plugins that will work with your plugin to achieve this. It would actually be good to be able to assign the shipping based on district and ward as some districts like Binh Thanh run from District 1 all the way to Go Vap and would have different prices in delivery apps.

Cheers

**Comment by htdat** [comment]
Hi, 

It's not possible yet in Woo Viet. This request was logged here https://github.com/htdat/woo-viet/issues/16

Generally, other plugins supporting this feature may not be compatible with Woo Viet. Please double check about this.

**Comment by Longkt** [comment]
Hi @gallnomad 

I've created a development branch for Shipping City (District) before
https://github.com/Longkt/woo-viet/tree/1.4-dev-shipping-city

You can download this one and check this feature, screenshot for using https://cl.ly/fb4cc9d9a12b

Let me know how it goes.

**Comment by gallnomad** [comment]
Hi Long,
Thanks again for your input you have been really helpful.

I have installed the WC City Plugin and downloaded the files from the link you sent above and uploaded them to the server into the wooviet plugin directory. But still it doesn't seem to be working. Perhaps I have not installed correctly or have the wrong code in the functions.php.

Could you let me know if I have installed correctly as what I have written above and if yes, can you give me an example of the way the code should be in the functions.php.

Cheers

**Comment by gallnomad** [comment]
Sorry Long looks like it is working now but everytime i install it there is a plugin update for woo viet so your files are overwriting something and Wordpress thinks it should have a plugin update. Any chance the files you have in dev are going to be put into the core plugin anytime soon?
