### ISSUE TITLE
Lỗi chọn tỉnh và quận huyện

### ISSUE THREAD

**Issue by vanh210** [htdat/woo-viet#82]
Khi chọn tỉnh khác, thì quận huyện không tạo options để chọn, phải load lại trang 
![image](https://user-images.githubusercontent.com/69494525/115401908-1da07500-a215-11eb-98c1-33c1aa6c66cc.png)

**Comment by htdat** [comment]
Hi, cảm ơn bạn. Bạn có thể gửi cho mình WooCommerce System Status report để mình thử replicate lỗi này được không? 

Bạn có thể tìm thông tin này ở đây https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/#section-1

**Lưu ý: Bỏ các thông tin nhạy cảm như website của bạn đi nhé. Mình quan tâm đến các phiên bản và các plugin/theme bạn đang dùng.**

**Comment by htdat** [comment]
Đóng issue vì (1) không có phản hồi, (2) đã check với Storefront các phiên bản cập nhất: WC 5.7.1, WP 5.8.1 và ko có vấn đề gì.
