### ISSUE TITLE
Lỗi on-hold khi thanh toán với coupon

### ISSUE THREAD

**Issue by khuuthuyky123** [htdat/woo-viet#84]
Khi em sử dụng coupon để thanh toán thì đơn hàng sẽ bị đánh là on-hold. Và chức năng refund cũng không thực hiện được với tiền VND
`
### WordPress Environment ###

WordPress address (URL): http://localhost:8080
Site address (URL): http://localhost:8080
WC Version: 5.4.1
REST API Version: ✔ 5.4.1
WC Blocks Version: ✔ 5.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.3.1
Log Directory Writable: ✔
WP Version: ❌ 5.7.2 - Một phiên bản mới của WordPress đang có sẵn (5.8)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: vi
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.38 (Debian)
PHP Version: 7.4.20
PHP Post Max Size: 13 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.64.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.7.34
Max Upload Size: 12 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Máy chủ của bạn chưa bật lớp SoapClient - một số gói mở rộng sử dụng cổng kết nối SOAP có thể không hoạt động như mong đợi.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.4.1
WC Database Prefix: wp_
Kích thước tổng dữ liệu: 4.87MB
Kích thước cơ sở dữ liệu: 3.35MB
Kích thước chỉ mục dữ liệu: 1.52MB
wp_woocommerce_sessions: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.14MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.17MB + Index: 0.14MB + Engine InnoDB
wp_posts: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 9
custom_css: 1
customize_changeset: 15
page: 7
post: 2
product: 2
revision: 12
shop_order: 44
shop_order_refund: 1

### Security ###

Secure connection (HTTPS): ❌
					Cửa hàng của bạn không sử dụng giao thức an toàn HTTPS. Tìm hiểu thêm về chứng chỉ bảo mật HTTPS và SSL .
Hide errors from visitors: ✔

### Active Plugins (9) ###

VNPAY: bởi VNPAY – 1.0.2
Buy Now Button for WooCommerce: bởi wpismylife – 1.0.0
Loco Translate: bởi Tim Whitlock – 2.5.3
My Plugin: bởi Khuu Thuy Ky – 0.3.1
Thankyou Coupons for WC: bởi Chris Bibby – 2.0.7
Woo Viet - WooCommerce for Vietnam: bởi htdat – 1.5.1
WooCommerce PayPal Checkout Gateway: bởi WooCommerce – 2.1.2
WooCommerce PayPal Payments: bởi WooCommerce – 1.3.2
WooCommerce: bởi Automattic – 5.4.1 (update to version 5.5.2 is available)

### Settings ###

API Enabled: –
Force SSL: –
Currency: VND (VND)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop mặc định: #6 - /shop/
Giỏ hàng: #7 - /cart/
Thanh toán: #8 - /
Tài khoản: #9 - /my-account/
Quy định và Điều kiện: ❌ Trang chưa được đặt

### Theme ###

Name: Storefront
Version: 3.7.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – Bạn nên sử dụng giao diện con cho việc sửa chữa trên giao diện hiện tại. Xemcách tạo giao diện con
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Hoàn tất: 82
Oldest: 2021-07-03 02:40:52 +0000
Newest: 2021-07-11 03:43:01 +0000

Đang chờ xử lý: 2
Oldest: 2021-07-27 08:11:35 +0000
Newest: 2021-07-27 08:31:47 +0000

### Status report information ###

Generated at: 2021-07-27 09:13:28 +00:00
`

**Comment by htdat** [comment]
> Khi em sử dụng coupon để thanh toán thì đơn hàng sẽ bị đánh là on-hold. 

- Bạn check lại xem nếu sử dụng với 2 plugin `Woo Viet` và WooCommerce còn bị lỗi trên không? 

> Và chức năng refund cũng không thực hiện được với tiền VND? 

Bạn dùng chức năng gì của Woo Viet và cổng thanh toán nào? 

---- 

**Lưu ý là mình chỉ support cho plugin Woo Viet, còn các vấn đề chung về WooCommerce bạn vui lòng nhận hỗ trợ ở đây https://wordpress.org/support/plugin/woocommerce/**

**Comment by khuuthuyky123** [comment]
có vẻ như on-hold là do plugin khác can thiệp vào. khi dùng các plugin woocommerce, woo viet và PayPal Express Checkout thì không xảy ra lỗi on-hold. 
Em sử dụng chỉ các tính năng 
<img width="728" alt="Screen Shot 2021-07-27 at 17 58 20" src="https://user-images.githubusercontent.com/45907363/127147856-cb89dd59-7226-4635-a56f-7053b3b3bd28.png">

Tuy nhiên chức năng refund của PayPal Express Checkout bị lỗi như hình. 
 [
<img width="611" alt="Screen Shot 2021-07-27 at 17 57 45" src="https://user-images.githubusercontent.com/45907363/127147747-4d71f0ba-a1b4-44f0-ba73-56b174b7f427.png">
](url)

**Comment by htdat** [comment]
> có vẻ như on-hold là do plugin khác can thiệp vào. khi dùng các plugin woocommerce, woo viet và PayPal Express Checkout thì không xảy ra lỗi on-hold.

Vâỵ bạn check thêm các plugin khác nhé. 

> Tuy nhiên chức năng refund của PayPal Express Checkout bị lỗi như hình.

Đúng rồi, mình chỉ hỗ trợ ở trang checkout thôi. Bạn nện refund bằng tay, trực tiếp ở trong PayPal nhé. 

@Longkt ^
